import type { Article, Video, StudyTool, VestibularTip, Subject, SubjectInfo } from "./types";

export const SUBJECTS: Record<Subject, SubjectInfo> = {
  matematica: { label: "Matemática", badge: "bg-blue-700 text-white", bg: "bg-blue-50", text: "text-blue-700", border: "border-blue-700", emoji: "📐" },
  portugues: { label: "Português", badge: "bg-amber-700 text-white", bg: "bg-amber-50", text: "text-amber-700", border: "border-amber-700", emoji: "📖" },
  historia: { label: "História", badge: "bg-orange-700 text-white", bg: "bg-orange-50", text: "text-orange-700", border: "border-orange-700", emoji: "🏛️" },
  geografia: { label: "Geografia", badge: "bg-green-700 text-white", bg: "bg-green-50", text: "text-green-700", border: "border-green-700", emoji: "🌎" },
  biologia: { label: "Biologia", badge: "bg-emerald-700 text-white", bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-700", emoji: "🔬" },
  quimica: { label: "Química", badge: "bg-violet-700 text-white", bg: "bg-violet-50", text: "text-violet-700", border: "border-violet-700", emoji: "⚗️" },
  fisica: { label: "Física", badge: "bg-red-700 text-white", bg: "bg-red-50", text: "text-red-700", border: "border-red-700", emoji: "⚡" },
  literatura: { label: "Literatura", badge: "bg-pink-700 text-white", bg: "bg-pink-50", text: "text-pink-700", border: "border-pink-700", emoji: "📚" },
  filosofia: { label: "Filosofia", badge: "bg-indigo-700 text-white", bg: "bg-indigo-50", text: "text-indigo-700", border: "border-indigo-700", emoji: "💭" },
  sociologia: { label: "Sociologia", badge: "bg-cyan-700 text-white", bg: "bg-cyan-50", text: "text-cyan-700", border: "border-cyan-700", emoji: "👥" },
  vestibular: { label: "Vestibular", badge: "bg-rose-700 text-white", bg: "bg-rose-50", text: "text-rose-700", border: "border-rose-700", emoji: "🎓" },
};

export const articles: Article[] = [
  {
    id: "1",
    title: "Equação do Segundo Grau: Fórmula de Bhaskara e Exercícios",
    excerpt: "Aprenda a resolver equações do segundo grau usando a fórmula de Bhaskara com exemplos práticos e exercícios resolvidos passo a passo.",
    subject: "matematica",
    author: "Prof. Carlos Souza",
    date: "15 mai. 2026",
    readTime: 8,
    slug: "equacao-segundo-grau-bhaskara",
    featured: true,
  },
  {
    id: "2",
    title: "Concordância Verbal: Regras Essenciais com Exemplos",
    excerpt: "Domine as principais regras de concordância verbal do português e evite os erros mais comuns na escrita e na fala.",
    subject: "portugues",
    author: "Prof.ª Ana Lima",
    date: "12 mai. 2026",
    readTime: 6,
    slug: "concordancia-verbal-regras-exemplos",
    featured: true,
  },
  {
    id: "3",
    title: "Primeira Guerra Mundial: Causas, Desenvolvimento e Consequências",
    excerpt: "Entenda os fatores que desencadearam a Primeira Guerra Mundial, os principais conflitos e as transformações geopolíticas que se seguiram.",
    subject: "historia",
    author: "Prof. Roberto Farias",
    date: "10 mai. 2026",
    readTime: 12,
    slug: "primeira-guerra-mundial",
    featured: true,
  },
  {
    id: "4",
    title: "Fotossíntese: Como as Plantas Produzem Energia",
    excerpt: "Compreenda o processo de fotossíntese, os pigmentos envolvidos, as fases clara e escura e a importância desse processo para a vida na Terra.",
    subject: "biologia",
    author: "Prof.ª Maria Santos",
    date: "08 mai. 2026",
    readTime: 7,
    slug: "fotossintese-como-plantas-produzem-energia",
  },
  {
    id: "5",
    title: "Climas do Brasil: Características e Distribuição",
    excerpt: "Conheça os diferentes tipos de clima no Brasil, suas características regionais e como influenciam a biodiversidade e a economia do país.",
    subject: "geografia",
    author: "Prof. Paulo Mendes",
    date: "05 mai. 2026",
    readTime: 9,
    slug: "climas-do-brasil",
  },
  {
    id: "6",
    title: "Ligações Químicas: Iônica, Covalente e Metálica",
    excerpt: "Aprenda como os átomos se unem para formar moléculas e compostos, explorando os três tipos principais de ligações químicas.",
    subject: "quimica",
    author: "Prof.ª Fernanda Costa",
    date: "03 mai. 2026",
    readTime: 10,
    slug: "ligacoes-quimicas",
  },
  {
    id: "7",
    title: "Leis de Newton: Os Três Princípios da Mecânica",
    excerpt: "Explore as três leis do movimento de Newton, compreenda seus fundamentos e veja como aplicá-las na resolução de problemas de física.",
    subject: "fisica",
    author: "Prof. André Alves",
    date: "01 mai. 2026",
    readTime: 8,
    slug: "leis-de-newton",
  },
  {
    id: "8",
    title: "Romantismo Brasileiro: Características e Autores",
    excerpt: "Conheça o movimento romântico no Brasil, seus principais autores, obras e as características que marcaram essa escola literária.",
    subject: "literatura",
    author: "Prof.ª Juliana Ramos",
    date: "28 abr. 2026",
    readTime: 11,
    slug: "romantismo-brasileiro",
  },
  {
    id: "9",
    title: "Iluminismo: Pensamento e Influência na Modernidade",
    excerpt: "Entenda os principais ideais do Iluminismo, os filósofos que moldaram esse movimento e sua influência nas revoluções e na sociedade moderna.",
    subject: "filosofia",
    author: "Prof. Marcos Oliveira",
    date: "25 abr. 2026",
    readTime: 9,
    slug: "iluminismo-pensamento-modernidade",
  },
  {
    id: "10",
    title: "Estratificação Social: Conceitos e Tipos",
    excerpt: "Compreenda como a sociedade se organiza em camadas, os critérios de estratificação e as implicações das desigualdades sociais.",
    subject: "sociologia",
    author: "Prof.ª Carla Vieira",
    date: "22 abr. 2026",
    readTime: 7,
    slug: "estratificacao-social",
  },
];

export const videos: Video[] = [
  {
    id: "1",
    title: "Funções do 1º e 2º Grau — Resolução Comentada",
    subject: "matematica",
    teacher: "Prof. Carlos Souza",
    duration: "18:42",
    views: "12,4 mil",
  },
  {
    id: "2",
    title: "Como Fazer uma Boa Redação para o ENEM",
    subject: "portugues",
    teacher: "Prof.ª Ana Lima",
    duration: "25:10",
    views: "34,1 mil",
  },
  {
    id: "3",
    title: "Revolução Francesa — Resumo Completo",
    subject: "historia",
    teacher: "Prof. Roberto Farias",
    duration: "22:35",
    views: "18,7 mil",
  },
  {
    id: "4",
    title: "Sistema Digestório Humano",
    subject: "biologia",
    teacher: "Prof.ª Maria Santos",
    duration: "15:20",
    views: "9,3 mil",
  },
  {
    id: "5",
    title: "Eletrostática: Cargas e Campo Elétrico",
    subject: "fisica",
    teacher: "Prof. André Alves",
    duration: "30:15",
    views: "7,8 mil",
  },
  {
    id: "6",
    title: "Tabela Periódica: Grupos e Períodos",
    subject: "quimica",
    teacher: "Prof.ª Fernanda Costa",
    duration: "20:45",
    views: "11,2 mil",
  },
];

export const vestibularTips: VestibularTip[] = [
  {
    id: "1",
    title: "Monte um Cronograma de Estudos",
    icon: "📅",
    content: "Organize seu tempo distribuindo as matérias ao longo da semana, priorizando aquelas com maior peso no ENEM. Reserve horários fixos e respeite as pausas para não se sobrecarregar.",
  },
  {
    id: "2",
    title: "Pratique com Provas Anteriores",
    icon: "📝",
    content: "Resolver provas dos anos anteriores é uma das melhores formas de entender o estilo das questões, identificar pontos fracos e ganhar velocidade na resolução.",
  },
  {
    id: "3",
    title: "Domine a Redação",
    icon: "✍️",
    content: "A redação vale 20% da nota do ENEM. Treine escrever textos dissertativo-argumentativos semanalmente e peça feedback. Atenção à estrutura: introdução, desenvolvimento e conclusão.",
  },
  {
    id: "4",
    title: "Cuide da Saúde",
    icon: "💪",
    content: "Sono de qualidade, alimentação equilibrada e atividade física são essenciais para manter o foco e a memória. Não abra mão do descanso nas vésperas da prova.",
  },
  {
    id: "5",
    title: "Revise os Conteúdos de Alto Impacto",
    icon: "🎯",
    content: "Foque nos tópicos que aparecem com mais frequência nas provas. Use a Matriz de Referência do ENEM como guia e priorize o que rende mais pontos.",
  },
  {
    id: "6",
    title: "Use Técnicas de Memorização",
    icon: "🧠",
    content: "Mapas mentais, flashcards e a técnica Pomodoro são ferramentas poderosas para fixar conteúdo, manter a concentração e tornar o estudo mais eficiente.",
  },
];

export const studyTools: StudyTool[] = [
  {
    id: "1",
    name: "Timer Pomodoro",
    description: "Divida seus estudos em blocos de 25 minutos com pausas curtas para manter o foco e evitar o cansaço mental.",
    icon: "⏱️",
    category: "Produtividade",
    url: "#",
  },
  {
    id: "2",
    name: "Mapas Mentais",
    description: "Organize ideias e conceitos de forma visual para facilitar a compreensão e a memorização de conteúdos complexos.",
    icon: "🗺️",
    category: "Organização",
    url: "#",
  },
  {
    id: "3",
    name: "Flashcards Digitais",
    description: "Crie e revise cartões de memória usando o método da repetição espaçada para fixar fórmulas, datas e conceitos.",
    icon: "🃏",
    category: "Memorização",
    url: "#",
  },
  {
    id: "4",
    name: "Simulado ENEM",
    description: "Pratique com questões no estilo ENEM e receba um relatório detalhado do seu desempenho por área do conhecimento.",
    icon: "📊",
    category: "Avaliação",
    url: "#",
  },
  {
    id: "5",
    name: "Calculadora SISU",
    description: "Calcule sua nota e descubra em quais cursos e universidades você pode ingressar com base na sua pontuação do ENEM.",
    icon: "🧮",
    category: "Planejamento",
    url: "#",
  },
  {
    id: "6",
    name: "Biblioteca Virtual",
    description: "Acesse resumos, apostilas e materiais de estudo organizados por matéria, nível e tema para complementar seus estudos.",
    icon: "📚",
    category: "Recursos",
    url: "#",
  },
];
